name: Keepalive

on:
  # At 8:40 PM UTC, on day 21 of the month
  schedule:
    - cron: '40 20 21 * *'
  workflow_dispatch:

jobs:
  keepalive:
    name: Keepalive
    # Only run cron on the tractorcow-farm account
    if: (github.event_name == 'schedule' && github.repository_owner == 'tractorcow-farm') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
